#
# BINDING REQUIRE
#
# USER-DB-URL
# USER-DB-USERNAME
# USER-DB-PASSWORD
# REDIS-HOST
# REDIS-PORT
# JWT-SECRET
# JWT-ACCESS-EXPIRE-TIME
# JWT-REFRESH-EXPIRE-TIME
# COOLSMS-API-KEY
# COOLSMS-API-SECRET-KEY
# COOLSMS-SEND-PHONE-NUMBER

server:
  port: 9002

spring:
  datasource:
    url: ${USER-DB-URL}
    username: ${USER-DB-USERNAME}
    password: ${USER-DB-PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
        auto_quote_keyword: true
        globally_quoted_identifiers: true

  redis:
    host: ${REDIS-HOST}
    port: ${REDIS-PORT}

logging:
  level:
    org:
      hibernate:
        SQL: trace

jwt:
  secret: ${JWT-SECRET}
  access-expire-time: ${JWT-ACCESS-EXPIRE-TIME}
  refresh-expire-time: ${JWT-REFRESH-EXPIRE-TIME}

coolsms:
  api-key: ${COOLSMS-API-KEY}
  api-secret-key: ${COOLSMS-API-SECRET-KEY}
  send-phone-number: ${COOLSMS-SEND-PHONE-NUMBER}