apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-bookulove-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /api($|/)(.*)
        backend:
          {{- $apigateway := index .Values "apigateway-service" }}
          service:
            name: {{ include "service.release.name" (list . $apigateway.metadata.name) }}
            port:
              number: {{ $apigateway.server.port }}
