{{- $ingress := .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-bookulove-websocket-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if $ingress.tls.enabled }}
    {{- $issuerType := "issuer" }}
    {{- if and $ingress.tls.issuer.type (eq $ingress.tls.issuer.type "ClusterIssuer") }}
    {{- $issuerType = "cluster-issuer"}}
    {{- end }}
    cert-manager.io/{{ $issuerType }}: {{ $ingress.tls.issuer.name }}
    {{- end }}
    # https://github.com/nginxinc/kubernetes-ingress/tree/main/examples/ingress-resources/websocket
    nginx.org/websocket-services: "{{ include "service.release.name" (list . "chatting-service") }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  {{- if $ingress.tls.enabled  }}
  tls:
  - secretName: {{ $ingress.tls.secret.name }}
    hosts: [ {{ $ingress.host | quote }} ]
  {{- end }}
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /api/chatting-service/stomps
        {{- $chattingService := index .Values "chatting-service" }}
        backend:
          service:
            name: {{ include "service.release.name" (list . $chattingService.metadata.name) }}
            port:
                number: {{ $chattingService.server.port }}
    {{- if $ingress.host }}
    host: {{ $ingress.host }}
    {{- end }}
