#
# BINDING REQUIRE
#
# CHAT-DB-URL
# CHAT-DB-USERNAME
# CHAT-DB-PASSWORD
# REDIS-HOST
# REDIS-PORT
# JWT-SECRET

server:
  port: 9005

spring:
  datasource:
    url: ${CHAT-DB-URL}
    username: ${CHAT-DB-USERNAME}
    password: ${CHAT-DB-PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
        globally_quoted_identifiers: true

  redis:
    host: ${REDIS-HOST}
    port: ${REDIS-PORT}

jwt:
  secret: ${JWT-SECRET}
