global:
  auth:
    password: &globalAuthPassword bookulove
  persistence:
    storage:
      storageClass: &globalStorageClass standard

auth-redis:
  auth:
    password: *globalAuthPassword
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0
    persistence:
      enabled: false

user-db:
  auth:
    password: *globalAuthPassword
  offsetServerID: 1000
  initDBScripts: &mySQLInitDBScripts
    00-bookulove-database.sql: |
      CREATE DATABASE IF NOT EXISTS `bookulove` DEFAULT CHARSET='utf8mb4' COLLATE='utf8mb4_unicode_ci';
  persistence:
    storage:
      storageClass: *globalStorageClass
      size: 1Gi

book-db:
  offsetServerID: 2000
  auth:
    password: *globalAuthPassword
  initDBScripts: *mySQLInitDBScripts
  persistence:
    storage:
      storageClass: *globalStorageClass
      size: 1Gi

chatting-db:
  offsetServerID: 3000
  auth:
    password: *globalAuthPassword
  initDBScripts: *mySQLInitDBScripts
  persistence:
    storage:
      storageClass: *globalStorageClass
      size: 1Gi

notification-db:
  offsetServerID: 4000
  auth:
    password: *globalAuthPassword
  initDBScripts: *mySQLInitDBScripts
  persistence:
    storage:
      storageClass: *globalStorageClass
      size: 1Gi

universe-db:
  offsetServerID: 9999
  auth:
    password: *globalAuthPassword
  persistence:
    storage:
      storageClass: *globalStorageClass
      size: 4Gi
  multiSourceReplication:
    sources:
    - &aboutReplicationSource
      name: user-db
      port: 3306
      user: root
      password: MYSQL_ROOT_PASSWORD
      filters:
      - "REPLICATE_DO_DB = (`bookulove`)"
    - !!merge <<: *aboutReplicationSource
      name: book-db
    - !!merge <<: *aboutReplicationSource
      name: chatting-db
    - !!merge <<: *aboutReplicationSource
      name: notification-db
